### ISSUE TITLE
MMDit error

### ISSUE THREAD

**Issue by exdysa** [hiddenswitch/ComfyUI#14]
### Expected Behavior

- brand new install of hiddenswitch, v excited lets goooooo
- run command
- wait for 127.0.0.1:8188 message

### Actual Behavior

- encounter an error
- `ModuleNotFoundError: No module named 'comfy.ldm.aura'`
- cry

![Screenshot 2024-07-16 181414](https://github.com/user-attachments/assets/3d6aea6d-851b-414e-a980-7e7ea2789247)

### Steps to Reproduce

type `comfyui` in your CLI of choice, though you must consult an AI assistant on which to choose, as it is beyond the scope of this issue report.

### Debug Logs

```powershell
(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>comfyui --force-fp16 --output-directory 
c:\users\public\extra_models\output --disable-known-models
Total VRAM 4096 MB, total RAM 8065 MB
pytorch version: 2.3.1+cu121
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1050 Ti : native
Using pytorch cross attention
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Public\.venv_hiddenswitch\Scripts\comfyui.exe\__main__.py", line 7, in <module>
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\cmd\main.py", line 227, in entrypoint
    asyncio.run(main())
  File "C:\Users\Public\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\cmd\main.py", line 149, in main
    server.nodes = import_all_nodes_in_workspace()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\nodes\package.py", line 108, in import_all_nodes_in_workspace
    from . import base_nodes
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\nodes\base_nodes.py", line 17, in <module>
    from .. import diffusers_load
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\diffusers_load.py", line 5, in <module>
    from . import sd, utils
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\sd.py", line 15, in <module>
    from . import lora
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\lora.py", line 3, in <module>
    from . import model_base
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\model_base.py", line 20, in <module>
    from .ldm.aura.mmdit import MMDiT as AuraMMDiT
ModuleNotFoundError: No module named 'comfy.ldm.aura'

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>
```

### Other

ur the best 🤍 thank you for your patience & understanding

**Comment by doctorpangloss** [comment]
this was resolved by https://github.com/hiddenswitch/ComfyUI/commit/a20bf8134d743a35ca65ac5720f08ba4d63e4da0

**Comment by exdysa** [comment]
I still get this error 

Using pytorch cross attention
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Public\.venv_hiddenswitch\Scripts\comfyui.exe\__main__.py", line 7, in <module>
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\cmd\main.py", line 227, in entrypoint
    asyncio.run(main())
  File "C:\Users\Public\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\cmd\main.py", line 149, in main
    server.nodes = import_all_nodes_in_workspace()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\nodes\package.py", line 108, in import_all_nodes_in_workspace
    from . import base_nodes
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\nodes\base_nodes.py", line 17, in <module>
    from .. import diffusers_load
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\diffusers_load.py", line 5, in <module>
    from . import sd, utils
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\sd.py", line 15, in <module>
    from . import lora
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\lora.py", line 3, in <module>
    from . import model_base
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\model_base.py", line 20, in <module>
    from .ldm.aura.mmdit import MMDiT as AuraMMDiT
ModuleNotFoundError: No module named 'comfy.ldm.aura'

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>

Even after pio updating. Should I reinstall?

**Comment by doctorpangloss** [comment]
Can you share the workflow you are using?

**Comment by doctorpangloss** [comment]
okay, it seems like you didn't quite upgrade yet.

**Comment by exdysa** [comment]
> Can you share the workflow you are using?
I can't, because I cant open the program.

**Comment by exdysa** [comment]
> okay, it seems like you didn't quite upgrade yet.

soooo how is it supposed to upgrade? i put the command as demonstrated in [18](https://github.com/hiddenswitch/ComfyUI/issues/18#issue-2430834226), how should it be done instead?

**Comment by exdysa** [comment]
okay so here is whats happening

- I have a new venv which is venv_hiddenswitch
- I still have an old venv with hiddenswitch installed

(.venv_hiddenswitch) C:\Users\Public>where comfyui
C:\Users\Public\.venv_hiddenswitch\Scripts\comfyui.exe
c:\Users\Public\.ui\Scripts\comfyui.exe

- running update from .venv_hiddenswitch, then running comfyui no args gives me comfy.ldm.aura module failure
- running update from .ui and then running comfyui no args from .ui DOES start comfyui
- running update from .ui, then running comfyui no args in .venv_hiddenswitch still does not work and continues to throw the error

Is this from both systems being different .venvs but attempting to use the same install location somewhere?
