### ISSUE TITLE
Installer forcing torch2.4

### ISSUE THREAD

**Issue by exdysa** [hiddenswitch/ComfyUI#18]
### Your question

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>pip install --upgrade git+https://github.com/hiddenswitch/ComfyUI.git

But I dont want 2.4...

![Screenshot 2024-07-25 150400](https://github.com/user-attachments/assets/22abf5b1-869f-49b7-9825-a8e7caffdab0)

### Logs

```powershell
(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>pip install --upgrade git+https://github.com/hiddenswitch/ComfyUI.git
Collecting git+https://github.com/hiddenswitch/ComfyUI.git
  Cloning https://github.com/hiddenswitch/ComfyUI.git to c:\users\woof\appdata\local\temp\pip-req-build-frgegomm
  Running command git clone --filter=blob:none --quiet https://github.com/hiddenswitch/ComfyUI.git 'C:\Users\woof\AppData\Local\Temp\pip-req-build-frgegomm'
  Resolved https://github.com/hiddenswitch/ComfyUI.git to commit 5c5e101ba3639af2c0448227c8ac09b2d123cf1e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torch@ https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl#sha256=b5c27549daf5f3209da6e07607f2bb8d02712555734fcd8cd7a23703a6e7d639 (from comfyui==0.0.1)
  Downloading https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl (2441.9 MB)
     ---------------------------------------- 2.4/2.4 GB 469.2 kB/s eta 0:00:00
Collecting torchvision@ https://download.pytorch.org/whl/cu121/torchvision-0.19.0%2Bcu121-cp312-cp312-win_amd64.whl#sha256=43c7b72a45360959b518a273b1c217ea5992da39e99b498cea8b19766954513c (from comfyui==0.0.1)
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.19.0%2Bcu121-cp312-cp312-win_amd64.whl (5.8 MB)
     ---------------------------------------- 5.8/5.8 MB 11.5 MB/s eta 0:00:00
Collecting clip@ git+https://github.com/openai/CLIP.git@main#egg=clip (from comfyui==0.0.1)
  Cloning https://github.com/openai/CLIP.git (to revision main) to c:\users\woof\appdata\local\temp\pip-install-awo_xdjw\clip_3e6393e57508415ea3ae3576cabc1e26
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\woof\AppData\Local\Temp\pip-install-awo_xdjw\clip_3e6393e57508415ea3ae3576cabc1e26'
  Resolved https://github.com/openai/CLIP.git to commit dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting huggingface-extra-chat-templates@ git+https://github.com/AppMana/appmana-comfyui-chat-templates.git (from comfyui==0.0.1)
  Cloning https://github.com/AppMana/appmana-comfyui-chat-templates.git to c:\users\woof\appdata\local\temp\pip-install-awo_xdjw\huggingface-extra-chat-templates_0e8e756f38dc4e5fa3c590ebdb6fcd15
  Running command git clone --filter=blob:none --quiet https://github.com/AppMana/appmana-comfyui-chat-templates.git 'C:\Users\woof\AppData\Local\Temp\pip-install-awo_xdjw\huggingface-extra-chat-templates_0e8e756f38dc4e5fa3c590ebdb6fcd15'
  Resolved https://github.com/AppMana/appmana-comfyui-chat-templates.git to commit 887bf299f454ace63cd3044e4f0cb6b310b4d29f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torchdiffeq>=0.2.3 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.2.4)
Requirement already satisfied: torchsde>=0.2.6 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.2.6)
Requirement already satisfied: einops>=0.6.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.8.0)
Requirement already satisfied: open-clip-torch>=2.24.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (2.26.1)
Requirement already satisfied: transformers>=4.29.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (4.42.4)
Requirement already satisfied: tokenizers>=0.13.3 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.19.1)
Requirement already satisfied: sentencepiece in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.2.0)
Requirement already satisfied: peft>=0.10.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.11.1)
Requirement already satisfied: torchinfo in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.8.0)
Requirement already satisfied: safetensors>=0.4.2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.4.3)
Requirement already satisfied: bitsandbytes in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.43.1)
Requirement already satisfied: aiohttp>=3.8.4 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (3.9.5)
Requirement already satisfied: accelerate>=0.25.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.32.1)
Requirement already satisfied: pyyaml>=6.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (6.0.1)
Requirement already satisfied: scikit-image>=0.20.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.24.0)
Requirement already satisfied: jsonmerge>=1.9.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.9.2)
Requirement already satisfied: clean-fid>=0.1.35 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.1.35)
Requirement already satisfied: resize-right>=0.0.2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.0.2)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (4.10.0.84)
Requirement already satisfied: albumentations>=1.3.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.4.11)
Requirement already satisfied: aiofiles>=23.1.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (24.1.0)
Requirement already satisfied: frozendict>=2.3.6 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (2.9.0.post0)
Requirement already satisfied: importlib-resources in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (6.4.0)
Requirement already satisfied: Pillow in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (10.2.0)
Requirement already satisfied: scipy in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.14.0)
Requirement already satisfied: tqdm in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (4.66.4)
Requirement already satisfied: protobuf<5.0.0,>=3.20.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (4.25.3)
Requirement already satisfied: psutil in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (6.0.0)
Requirement already satisfied: ConfigArgParse in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.7)
Requirement already satisfied: aio-pika in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (9.4.2)
Requirement already satisfied: pyjwt[crypto] in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (2.8.0)
Requirement already satisfied: kornia>=0.7.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.7.3)
Requirement already satisfied: mpmath!=1.4.0a0,>=1.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.3.0)
Requirement already satisfied: huggingface-hub in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.23.5)
Requirement already satisfied: lazy-object-proxy in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.10.0)
Requirement already satisfied: lazy-loader>=0.3 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.4)
Requirement already satisfied: can-ada in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.3.0)
Requirement already satisfied: fsspec in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (2024.2.0)
Requirement already satisfied: natsort in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (8.4.0)
Requirement already satisfied: OpenEXR in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (3.2.4)
Requirement already satisfied: opentelemetry-distro in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.46b0)
Requirement already satisfied: opentelemetry-exporter-otlp in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.25.0)
Requirement already satisfied: opentelemetry-propagator-jaeger in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.25.0)
Requirement already satisfied: opentelemetry-instrumentation in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.46b0)
Requirement already satisfied: opentelemetry-util-http in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.46b0)
Requirement already satisfied: opentelemetry-instrumentation-aio-pika in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.46b0)
Requirement already satisfied: opentelemetry-instrumentation-requests in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.46b0)
Requirement already satisfied: opentelemetry-semantic-conventions in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.46b0)
Requirement already satisfied: wrapt>=1.16.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.16.0)
Requirement already satisfied: certifi in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (2024.7.4)
Requirement already satisfied: spandrel>=0.3.4 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.3.4)
Requirement already satisfied: numpy<2.0.0,>=1.24.4 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (1.26.3)
Requirement already satisfied: soundfile in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.12.1)
Requirement already satisfied: watchdog in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (4.0.1)
Requirement already satisfied: PySoundFile in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (0.9.0.post1)
Requirement already satisfied: networkx>=2.6.3 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from comfyui==0.0.1) (3.2.1)
Requirement already satisfied: packaging>=20.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from accelerate>=0.25.0->comfyui==0.0.1) (24.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aiohttp>=3.8.4->comfyui==0.0.1) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aiohttp>=3.8.4->comfyui==0.0.1) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aiohttp>=3.8.4->comfyui==0.0.1) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aiohttp>=3.8.4->comfyui==0.0.1) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aiohttp>=3.8.4->comfyui==0.0.1) (1.9.4)
Requirement already satisfied: typing-extensions>=4.9.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from albumentations>=1.3.0->comfyui==0.0.1) (4.9.0)
Requirement already satisfied: scikit-learn>=1.3.2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from albumentations>=1.3.0->comfyui==0.0.1) (1.5.1)
Requirement already satisfied: pydantic>=2.7.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from albumentations>=1.3.0->comfyui==0.0.1) (2.8.2)
Requirement already satisfied: albucore>=0.0.11 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from albumentations>=1.3.0->comfyui==0.0.1) (0.0.12)
Requirement already satisfied: eval-type-backport in c:\users\public\.venv_hiddenswitch\lib\site-packages (from albumentations>=1.3.0->comfyui==0.0.1) (0.2.0)
Requirement already satisfied: requests in c:\users\public\.venv_hiddenswitch\lib\site-packages (from clean-fid>=0.1.35->comfyui==0.0.1) (2.32.3)
Requirement already satisfied: jsonschema>2.4.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from jsonmerge>=1.9.0->comfyui==0.0.1) (4.23.0)
Requirement already satisfied: kornia-rs>=0.1.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from kornia>=0.7.0->comfyui==0.0.1) (0.1.5)
Requirement already satisfied: regex in c:\users\public\.venv_hiddenswitch\lib\site-packages (from open-clip-torch>=2.24.0->comfyui==0.0.1) (2024.5.15)
Requirement already satisfied: ftfy in c:\users\public\.venv_hiddenswitch\lib\site-packages (from open-clip-torch>=2.24.0->comfyui==0.0.1) (6.2.0)
Requirement already satisfied: timm in c:\users\public\.venv_hiddenswitch\lib\site-packages (from open-clip-torch>=2.24.0->comfyui==0.0.1) (1.0.7)
Requirement already satisfied: filelock in c:\users\public\.venv_hiddenswitch\lib\site-packages (from huggingface-hub->comfyui==0.0.1) (3.13.1)
Requirement already satisfied: six>=1.5 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from python-dateutil>=2.8.2->comfyui==0.0.1) (1.16.0)
Requirement already satisfied: imageio>=2.33 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from scikit-image>=0.20.0->comfyui==0.0.1) (2.34.2)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from scikit-image>=0.20.0->comfyui==0.0.1) (2024.7.2)
Requirement already satisfied: sympy in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch@ https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl#sha256=b5c27549daf5f3209da6e07607f2bb8d02712555734fcd8cd7a23703a6e7d639->comfyui==0.0.1) (1.12)
Requirement already satisfied: jinja2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch@ https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl#sha256=b5c27549daf5f3209da6e07607f2bb8d02712555734fcd8cd7a23703a6e7d639->comfyui==0.0.1) (3.1.3)
Requirement already satisfied: setuptools in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch@ https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl#sha256=b5c27549daf5f3209da6e07607f2bb8d02712555734fcd8cd7a23703a6e7d639->comfyui==0.0.1) (70.3.0)
Requirement already satisfied: trampoline>=0.1.2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torchsde>=0.2.6->comfyui==0.0.1) (0.1.2)
Requirement already satisfied: colorama in c:\users\public\.venv_hiddenswitch\lib\site-packages (from tqdm->comfyui==0.0.1) (0.4.6)
Requirement already satisfied: aiormq<6.9.0,>=6.8.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aio-pika->comfyui==0.0.1) (6.8.0)
Requirement already satisfied: opentelemetry-api~=1.12 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-distro->comfyui==0.0.1) (1.25.0)
Requirement already satisfied: opentelemetry-sdk~=1.13 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-distro->comfyui==0.0.1) (1.25.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc==1.25.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp->comfyui==0.0.1) (1.25.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http==1.25.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp->comfyui==0.0.1) (1.25.0)
Requirement already satisfied: deprecated>=1.2.6 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.25.0->opentelemetry-exporter-otlp->comfyui==0.0.1) (1.2.14)
Requirement already satisfied: googleapis-common-protos~=1.52 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.25.0->opentelemetry-exporter-otlp->comfyui==0.0.1) (1.63.2)
Requirement already satisfied: grpcio<2.0.0,>=1.0.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.25.0->opentelemetry-exporter-otlp->comfyui==0.0.1) (1.64.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.25.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.25.0->opentelemetry-exporter-otlp->comfyui==0.0.1) (1.25.0)
Requirement already satisfied: opentelemetry-proto==1.25.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.25.0->opentelemetry-exporter-otlp->comfyui==0.0.1) (1.25.0)
Requirement already satisfied: importlib-metadata<=7.1,>=6.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from opentelemetry-api~=1.12->opentelemetry-distro->comfyui==0.0.1) (7.1.0)
Requirement already satisfied: cryptography>=3.4.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from pyjwt[crypto]->comfyui==0.0.1) (42.0.8)
Requirement already satisfied: cffi>=0.6 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from PySoundFile->comfyui==0.0.1) (1.16.0)
Requirement already satisfied: pamqp==3.3.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from aiormq<6.9.0,>=6.8.0->aio-pika->comfyui==0.0.1) (3.3.0)
Requirement already satisfied: tomli>=2.0.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from albucore>=0.0.11->albumentations>=1.3.0->comfyui==0.0.1) (2.0.1)
Requirement already satisfied: pycparser in c:\users\public\.venv_hiddenswitch\lib\site-packages (from cffi>=0.6->PySoundFile->comfyui==0.0.1) (2.22)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from jsonschema>2.4.0->jsonmerge>=1.9.0->comfyui==0.0.1) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from jsonschema>2.4.0->jsonmerge>=1.9.0->comfyui==0.0.1) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from jsonschema>2.4.0->jsonmerge>=1.9.0->comfyui==0.0.1) (0.19.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from pydantic>=2.7.0->albumentations>=1.3.0->comfyui==0.0.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from pydantic>=2.7.0->albumentations>=1.3.0->comfyui==0.0.1) (2.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from requests->clean-fid>=0.1.35->comfyui==0.0.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from requests->clean-fid>=0.1.35->comfyui==0.0.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from requests->clean-fid>=0.1.35->comfyui==0.0.1) (2.2.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from scikit-learn>=1.3.2->albumentations>=1.3.0->comfyui==0.0.1) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from scikit-learn>=1.3.2->albumentations>=1.3.0->comfyui==0.0.1) (3.5.0)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from ftfy->open-clip-torch>=2.24.0->comfyui==0.0.1) (0.2.13)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from jinja2->torch@ https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl#sha256=b5c27549daf5f3209da6e07607f2bb8d02712555734fcd8cd7a23703a6e7d639->comfyui==0.0.1) (2.1.5)
Requirement already satisfied: zipp>=0.5 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from importlib-metadata<=7.1,>=6.0->opentelemetry-api~=1.12->opentelemetry-distro->comfyui==0.0.1) (3.19.2)
Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.3.1+cu121
    Uninstalling torch-2.3.1+cu121:
      Successfully uninstalled torch-2.3.1+cu121
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.18.1+cu121
    Uninstalling torchvision-0.18.1+cu121:
      Successfully uninstalled torchvision-0.18.1+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.1+cu121 requires torch==2.3.1+cu121, but you have torch 2.4.0+cu121 which is incompatible.
Successfully installed torch-2.4.0+cu121 torchvision-0.19.0+cu121

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>pip install torch=2.3.0+cu121 torchvision torchaudio --index-url=https://download.pytorch.org/whl/cu121
ERROR: Invalid requirement: 'torch=2.3.0+cu121': Expected end or semicolon (after name and no valid version specifier)
    torch=2.3.0+cu121
         ^
Hint: = is not a valid operator. Did you mean == ?

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>pip install torch==2.3.0+cu121 torchvision torchaudio --index-url=https://download.pytorch.org/whl/cu121
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch==2.3.0+cu121
  Using cached https://download.pytorch.org/whl/cu121/torch-2.3.0%2Bcu121-cp312-cp312-win_amd64.whl (2413.3 MB)
Requirement already satisfied: torchvision in c:\users\public\.venv_hiddenswitch\lib\site-packages (0.19.0+cu121)
Requirement already satisfied: torchaudio in c:\users\public\.venv_hiddenswitch\lib\site-packages (2.3.1+cu121)
Requirement already satisfied: filelock in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (4.9.0)
Requirement already satisfied: sympy in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (1.12)
Requirement already satisfied: networkx in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (3.1.3)
Requirement already satisfied: fsspec in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (2024.2.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torch==2.3.0+cu121) (2021.4.0)
Requirement already satisfied: numpy in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torchvision) (1.26.3)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.18.1%2Bcu121-cp312-cp312-win_amd64.whl (5.7 MB)
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.18.0%2Bcu121-cp312-cp312-win_amd64.whl (5.7 MB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from torchvision) (10.2.0)
INFO: pip is looking at multiple versions of torchaudio to determine which version is compatible with other requirements. This could take a while.
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu121/torchaudio-2.4.0%2Bcu121-cp312-cp312-win_amd64.whl (4.1 MB)
     ---------------------------------------- 4.1/4.1 MB 5.8 MB/s eta 0:00:00
  Using cached https://download.pytorch.org/whl/cu121/torchaudio-2.3.0%2Bcu121-cp312-cp312-win_amd64.whl (4.1 MB)
Requirement already satisfied: intel-openmp==2021.* in c:\users\public\.venv_hiddenswitch\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.0+cu121) (2021.4.0)
Requirement already satisfied: tbb==2021.* in c:\users\public\.venv_hiddenswitch\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.0+cu121) (2021.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from jinja2->torch==2.3.0+cu121) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in c:\users\public\.venv_hiddenswitch\lib\site-packages (from sympy->torch==2.3.0+cu121) (1.3.0)
Installing collected packages: torch, torchvision, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.4.0+cu121
    Uninstalling torch-2.4.0+cu121:
      Successfully uninstalled torch-2.4.0+cu121
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.19.0+cu121
    Uninstalling torchvision-0.19.0+cu121:
      Successfully uninstalled torchvision-0.19.0+cu121
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.3.1+cu121
    Uninstalling torchaudio-2.3.1+cu121:
      Successfully uninstalled torchaudio-2.3.1+cu121
Successfully installed torch-2.3.0+cu121 torchaudio-2.3.0+cu121 torchvision-0.18.0+cu121

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>comfyui
Total VRAM 4096 MB, total RAM 8065 MB
pytorch version: 2.3.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1050 Ti : native
Using pytorch cross attention
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Public\.venv_hiddenswitch\Scripts\comfyui.exe\__main__.py", line 7, in <module>
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\cmd\main.py", line 227, in entrypoint
    asyncio.run(main())
  File "C:\Users\Public\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\cmd\main.py", line 149, in main
    server.nodes = import_all_nodes_in_workspace()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Python\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\nodes\package.py", line 108, in import_all_nodes_in_workspace
    from . import base_nodes
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\nodes\base_nodes.py", line 17, in <module>
    from .. import diffusers_load
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\diffusers_load.py", line 5, in <module>
    from . import sd, utils
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\sd.py", line 15, in <module>
    from . import lora
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\lora.py", line 3, in <module>
    from . import model_base
  File "C:\Users\Public\.venv_hiddenswitch\Lib\site-packages\comfy\model_base.py", line 20, in <module>
    from .ldm.aura.mmdit import MMDiT as AuraMMDiT
ModuleNotFoundError: No module named 'comfy.ldm.aura'

(.venv_hiddenswitch) C:\Users\Public\hiddenswitch>
```
```


### Other

_No response_

**Comment by doctorpangloss** [comment]
Use

```
pip install --no-build-isolation --upgrade git+https://github.com/hiddenswitch/ComfyUI.git
```
to use the currently installed version of `torch` and `torchvision`.

**Comment by exdysa** [comment]
works, tested, thank you
