### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by tammba** [hiddenswitch/ComfyUI#22]
### Expected Behavior

I set it clearly according to the instructions via Powershell

### Actual Behavior

500 Internal Server Error
Server got itself in trouble 

### Steps to Reproduce

after pip install git+https://github.com/hiddenswitch/ComfyUI.git after installation, I did not see the directory with ComfyUI on the disk, it seemed very strange

### Debug Logs

```powershell
(venv) PS C:\HS> comfyui
C:\HS\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\HS\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
C:\HS\venv\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Starting server
To see the GUI go to: http://127.0.0.1:8188
Error handling request
Traceback (most recent call last):
  File "C:\HS\venv\lib\site-packages\aiohttp\web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
  File "C:\HS\venv\lib\site-packages\aiohttp\web_app.py", line 559, in _handle
    return await handler(request)
  File "C:\HS\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\HS\venv\lib\site-packages\comfy\vendor\aiohttp_server_instrumentation.py", line 196, in middleware
    or _excluded_urls.url_disabled(request.url.path)
  File "aiohttp\\_helpers.pyx", line 30, in aiohttp._helpers.reify.__get__
  File "C:\HS\venv\lib\site-packages\aiohttp\web_request.py", line 457, in url
    url = URL.build(scheme=self.scheme, host=self.host)
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 380, in build
    netloc = cls._make_netloc(
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 1052, in _make_netloc
    ret = cls._encode_host(host)
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 1033, in _encode_host
    _host_validate(host)
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 1602, in _host_validate
    raise ValueError(
ValueError: Host '127.0.0.1:8188' cannot contain ':' (at position 9)
Error handling request
Traceback (most recent call last):
  File "C:\HS\venv\lib\site-packages\aiohttp\web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
  File "C:\HS\venv\lib\site-packages\aiohttp\web_app.py", line 559, in _handle
    return await handler(request)
  File "C:\HS\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\HS\venv\lib\site-packages\comfy\vendor\aiohttp_server_instrumentation.py", line 196, in middleware
    or _excluded_urls.url_disabled(request.url.path)
  File "aiohttp\\_helpers.pyx", line 30, in aiohttp._helpers.reify.__get__
  File "C:\HS\venv\lib\site-packages\aiohttp\web_request.py", line 457, in url
    url = URL.build(scheme=self.scheme, host=self.host)
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 380, in build
    netloc = cls._make_netloc(
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 1052, in _make_netloc
    ret = cls._encode_host(host)
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 1033, in _encode_host
    _host_validate(host)
  File "C:\HS\venv\lib\site-packages\yarl\_url.py", line 1602, in _host_validate
    raise ValueError(
ValueError: Host '127.0.0.1:8188' cannot contain ':' (at position 9)
```

**Comment by doctorpangloss** [comment]
unfortunately this error was due to a [bad release from `aiohttp`](https://github.com/aio-libs/aiohttp/issues/9360) and affected many people for the last week

try `pip install -U aiohttp` to resolve the error

if you need to create the directories to fill with checkpoints, run

```
comfyui --create-directories
```

**Comment by tammba** [comment]
thanks
