### ISSUE TITLE
EmbeddedComfyClient does not respect cwd param in provided Configuration

### ISSUE THREAD

**Issue by yondonfu** [hiddenswitch/ComfyUI#25]
### Expected Behavior

I expect EmbeddedComfyClient to look for the `models` folder under the path specified via the `cwd` param in the provided Configuration.

### Actual Behavior

EmbeddedComfyClient looks for the `models` folder in the current directory that the calling script is running in.

### Steps to Reproduce

This is a `test.py` file:

```
import asyncio

from comfy.api.components.schema.prompt import Prompt
from comfy.cli_args_types import Configuration
from comfy.client.embedded_comfy_client import EmbeddedComfyClient

PROMPT = {
    "1": {
        "inputs": {"image": "example.png", "upload": "image"},
        "class_type": "LoadImage",
        "_meta": {"title": "Load Image"},
    },
    "2": {
        "inputs": {"engine": "depth_anything_v2_vitb-fp16.engine", "images": ["1", 0]},
        "class_type": "DepthAnythingTensorrt",
        "_meta": {"title": "Depth Anything Tensorrt"},
    },
    "3": {
        "inputs": {"images": ["2", 0]},
        "class_type": "PreviewImage",
        "_meta": {"title": "Preview Image"},
    },
}


async def main():
    cwd = "/home/user/comfy/ComfyUI"
    config = Configuration(cwd=cwd)
    client = EmbeddedComfyClient(config)

    prompt = Prompt.validate(PROMPT)
    await client.queue_prompt(prompt)


if __name__ == "__main__":
    asyncio.run(main())
```

1. Have a ComfyUI workspace under `/home/user/comfy/ComfyUI` with [this custom node](https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt) under `custom_nodes` and the file `depth_anything_v2_vitb-fp16.engine` under `models/tensorrt/depth-anything`.
2. `pip install comfyui @git+https://github.com/hiddenswitch/ComfyUI.git@89d07f3adf32a6703181343bc732bd85104bb653`
3. Run `python test.py` and notice that there are no prompt execution errors.
4. `pip uninstall comfyui`
5. `pip install comfyui@git+https://github.com/hiddenswitch/ComfyUI.git`
6. Run `python test.py` and notice there *are* prompt execution errors.

### Debug Logs

```powershell
Failed to validate prompt for output 3:
* DepthAnythingTensorrt 2:
  - Exception when validating inner node: [Errno 2] No such file or directory: '/home/user/test/models/tensorrt/depth-anything'
Output will be ignored
Traceback (most recent call last):
  File "/home/user/test/test.py", line 36, in <module>
    asyncio.run(main())
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/test/test.py", line 32, in main
    await client.queue_prompt(prompt)
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/opentelemetry/util/_decorator.py", line 68, in async_wrapper
    return await func(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/comfy/client/embedded_comfy_client.py", line 202, in queue_prompt
    return await get_event_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/comfy/client/embedded_comfy_client.py", line 44, in _execute_prompt
    return __execute_prompt(prompt, prompt_id, client_id, span_context, progress_handler, configuration)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/comfy/client/embedded_comfy_client.py", line 100, in __execute_prompt
    raise exc_info
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/comfy/client/embedded_comfy_client.py", line 87, in __execute_prompt
    raise ValueError(json.dumps(validation_error_dict))
ValueError: {"2": {"errors": [{"type": "exception_during_inner_validation", "message": "Exception when validating inner node", "details": "[Errno 2] No such file or directory: '/home/user/test/models/tensorrt/depth-anything'", "extra_info": {"input_name": "images", "input_config": ["IMAGE", {}], "exception_message": "[Errno 2] No such file or directory: '/home/user/test/models/tensorrt/depth-anything'", "exception_type": "FileNotFoundError", "traceback": ["  File \"/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/comfy/cmd/execution.py\", line 718, in validate_inputs\n    r2 = validate_inputs(prompt, o_id, validated)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/comfy/cmd/execution.py\", line 644, in validate_inputs\n    class_inputs = obj_class.INPUT_TYPES()\n                   ^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/user/comfy/ComfyUI/custom_nodes/ComfyUI-Depth-Anything-Tensorrt/__init__.py\", line 18, in INPUT_TYPES\n    \"engine\": (os.listdir(ENGINE_DIR),),\n               ^^^^^^^^^^^^^^^^^^^^^^\n"], "linked_node": ["2", 0]}}], "dependent_outputs": ["3"], "class_type": "DepthAnythingTensorrt"}}
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1339, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1336, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "/home/user/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1323, in get_cache
    json_obj = await core.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 620, in get_data
    async with session.get(uri) as resp:
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/connector.py", line 1317, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/connector.py", line 971, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/connector.py", line 1002, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/site-packages/aiohttp/resolver.py", line 38, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/base_events.py", line 868, in getaddrinfo
    return await self.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/asyncio/base_events.py", line 830, in run_in_executor
    executor.submit(func, *args), loop=self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/hiddenswitch-test/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

### Other

I don't seem to encounter this issue at commit 89d07f3adf32a6703181343bc732bd85104bb653. But, I encounter this issue off the latest master.

**Comment by doctorpangloss** [comment]
thanks for reporting, i am updating these issues!
